[settings]
# 跑分测试前的缓存预热时间 (单位: 秒)
cache_duration=10

# 每个 CPU 核心进行跑分测试的时长 (单位: 秒)
benchmark_duration=25

# 指定要测试的 CPU 核心数组，使用逗号分隔
# 例如: 如果只想测试 CPU 1、CPU 3 和 CPU 6，请填写 [1,3,6] (顺序不重要)
# 例如: 如果只想测试 CPU 0 到 7，请填写 [0..7] (支持组合用法，例如 [0..7, 9, 11..13])
# 默认留空 [] 表示测试所有的核心
custom_cpus=[0..23]

# 1 表示使用 lava-triangle (Vulkan API)
# 2 表示使用 black-white-benchmark (D3D9 API)
api=1

# 是否让测试程序与显卡驱动使用相同的核心亲和性 (同步绑定)
# 开启此选项可以减少系统的上下文切换，从而提高跑分成绩的稳定性
# 但是由于和游戏抢占同一个核心，整体 FPS 可能会降低
sync_driver_affinity=true

# 禁用“按回车键开始测试”的提示，启动程序后自动开始跑分
skip_confirmation=false

[MSI Afterburner]
# 每次重启显卡驱动时，自动加载微星小飞机 (MSI Afterburner) 的超频预设配置文件，以保持超频状态
# 0 为默认值，表示不加载任何超频预设
profile=0

# 微星小飞机 MSIAfterburner.exe 的完整绝对路径，请勿加引号
location=C:\Program Files (x86)\MSI Afterburner\MSIAfterburner.exe

[xperf]
# 开启记录 DPC/ISR 的中断日志，并在跑分后生成分析报告
enabled=false

# 微软性能工具 xperf.exe 的完整绝对路径，请勿加引号
location=C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\xperf.exe

# 是否保存由 xperf 生成的原始 ETL 日志文件
# 警告: 开启此设置会在测试时产生数百 MB 甚至几个 GB 的庞大日志文件，非常占用硬盘空间
save_etls=false

[liblava]
# 开启独占全屏模式
fullscreen=true

# 窗口分辨率设置，仅在上方关闭了全屏模式 (fullscreen=false) 时该分辨率才会生效
x_resolution=1920
y_resolution=1080

# 游戏最大帧率限制，0 表示不锁帧 (让显卡跑满)
fps_cap=0

# 开启三重缓冲
triple_buffering=false
